### ISSUE TITLE
tip failed consistency check

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [iotaledger/iota.lib.py#126]
Hi! 

The `send_transfer.py` examples exits with the following exception:

```
iota.adapter.BadApiResponse: 400 response from node: starting tip failed consistency check
```
Do you have a hint how to resolve that issue? 

Regards and thanks in advance

PS.: running latest iri 1.4.1.4, connected to multiple neighbors. So, the infrastructure looks ok.

**Comment by HerrMuellerluedenscheid** [comment]
A quick followup. I just saw in the log of my iri the following:
```Jan 01 22:22:06 curiosity java[11233]: 01/01 22:22:06.354 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Transaction resolves to incorrect ledger balance: -6702017378961
```

**Comment by todofixthis** [comment]
Hey @HerrMuellerluedenscheid based on https://github.com/iotaledger/iri/blob/v1.4.1.4/src/main/java/com/iota/iri/service/TipsManager.java#L125 it appears that this error occurs when PyOTA sends a `getTransactionsToApprove` request (this can be confirmed by checking the traceback from the `BadApiResponse` exception).

Could you confirm?

**Comment by HerrMuellerluedenscheid** [comment]
Yes, that is correct. 
This is the logger output at debug level:
```
DEBUG:__main__:Sending post to http://localhost:14737: '{"command": "getTransactionsToApprove", "depth": 40}'
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:14737 "POST / HTTP/1.1" 400 148
DEBUG:__main__:Receiving post from http://localhost:14737: b'{"error":"starting tip failed consistency check: CFOEIMMZCJDQYEJPOGEPGXLNSNEFNTPHDWSQNCVSUXTYSISKFLZXKCHWGXUFBJMRKLNSGAMM9IPB99999","duration":7198}'
Traceback (most recent call last):
  File "send_transfer.py", line 63, in <module>
    message = TryteString.from_string('Hello!'),
  File "/home/marius/src/iota.lib.py/iota/api.py", line 877, in send_transfer
    minWeightMagnitude  = min_weight_magnitude,
  File "/home/marius/src/iota.lib.py/iota/commands/__init__.py", line 126, in __call__
    self.response = self._execute(self.request)
  File "/home/marius/src/iota.lib.py/iota/commands/extended/send_transfer.py", line 52, in _execute
    trytes              = pt_response['trytes'],
  File "/home/marius/src/iota.lib.py/iota/commands/__init__.py", line 126, in __call__
    self.response = self._execute(self.request)
  File "/home/marius/src/iota.lib.py/iota/commands/extended/send_trytes.py", line 42, in _execute
    gta_response = GetTransactionsToApproveCommand(self.adapter)(depth=depth)
  File "/home/marius/src/iota.lib.py/iota/commands/__init__.py", line 126, in __call__
    self.response = self._execute(self.request)
  File "/home/marius/src/iota.lib.py/iota/commands/__init__.py", line 154, in _execute
    return self.adapter.send_request(request)
  File "/home/marius/src/iota.lib.py/iota/adapter/__init__.py", line 301, in send_request
    return self._interpret_response(response, payload, {codes['ok']})
  File "/home/marius/src/iota.lib.py/iota/adapter/__init__.py", line 438, in _interpret_response
    'response': decoded,
iota.adapter.BadApiResponse: 400 response from node: starting tip failed consistency check: CFOEIMMZCJDQYEJPOGEPGXLNSNEFNTPHDWSQNCVSUXTYSISKFLZXKCHWGXUFBJMRKLNSGAMM9IPB99999
```

BTW: the `Transaction resolves to incorrect ledger balance` warning also persists. It shows up in the logs after waiting about 5 minutes after iri restart. However, this is probably rather something to discuss on the slack.

**Comment by HerrMuellerluedenscheid** [comment]
The example finally executed without problems. So, the problem was the iri which had an issue but was solved as described above.

Regards and thanks

M

**Comment by todofixthis** [comment]
Glad to hear you got it sorted!  Thanks for posting your findings!
