### ISSUE TITLE
Use PoWbox aka Sandbox

### ISSUE THREAD

**Issue by lapwat** [iotaledger/iota.lib.py#170]
Hello,

I'm trying to use the new powbox referenced in [the official post](https://blog.iota.org/relaunching-the-powbox-d392236b6939).
I use this code given in [Getting Started](https://github.com/iotaledger/iota.lib.py/blob/3c0cdf8b61ed651a4ba7221e9944c9f3e8e63836/docs/getting_started.rst#using-the-sandbox-node)
```python
self._api = Iota(adapter=SandboxAdapter(uri='https://powbox.testnet.iota.org', auth_token='token'), seed='seed')
```
I replaced the uri with the one given in the official post.

I get this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/iota/adapter/__init__.py", line 391, in _interpret_response
    decoded = json.loads(raw_content) # type: dict
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 14, in <module>
    tangle.send_transfers(transfers)
  File "/home/lapwat/Documents/lotiota/src/tangle.py", line 26, in send_transfers
    self._api.send_transfer(depth, transfers)
  File "/usr/lib/python3.6/site-packages/iota/api.py", line 922, in send_transfer
    minWeightMagnitude  = min_weight_magnitude,
  File "/usr/lib/python3.6/site-packages/iota/commands/__init__.py", line 130, in __call__
    self.response = self._execute(self.request)
  File "/usr/lib/python3.6/site-packages/iota/commands/extended/send_transfer.py", line 54, in _execute
    reference           = reference,
  File "/usr/lib/python3.6/site-packages/iota/commands/__init__.py", line 130, in __call__
    self.response = self._execute(self.request)
  File "/usr/lib/python3.6/site-packages/iota/commands/extended/send_trytes.py", line 45, in _execute
    reference=reference,
  File "/usr/lib/python3.6/site-packages/iota/commands/__init__.py", line 130, in __call__
    self.response = self._execute(self.request)
  File "/usr/lib/python3.6/site-packages/iota/commands/__init__.py", line 158, in _execute
    return self.adapter.send_request(request)
  File "/usr/lib/python3.6/site-packages/iota/adapter/sandbox.py", line 219, in send_request
    return super(SandboxAdapter, self).send_request(payload, **kwargs)
  File "/usr/lib/python3.6/site-packages/iota/adapter/__init__.py", line 304, in send_request
    return self._interpret_response(response, payload, {codes['ok']})
  File "/usr/lib/python3.6/site-packages/iota/adapter/sandbox.py", line 227, in _interpret_response
    expected_status = {codes['ok'], codes['accepted']},
  File "/usr/lib/python3.6/site-packages/iota/adapter/__init__.py", line 404, in _interpret_response
    'raw_response': raw_content,
iota.adapter.BadApiResponse: Non-JSON 404 response from node: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /commands</pre>
</body>
</html>
```
My questions are:
Where does this error come from ? Is my syntax good ? How to make it work ?
In the official post they use a provider & a powbox uris whereas in your python example you only use the powbox uri. Is it normal ?

Thank you a lot,
lapwat

**Comment by todofixthis** [comment]
Hey lapwat.  Thanks for reporting this!

It looks like the powbox node is sending a 404 response.  Perhaps the URL structure has changed since the sandbox node was decommissioned.

I'll have a bit of a chinwag to the powbox maintainer and see if we can get to the bottom of this.

**Comment by lapwat** [comment]
Hey, I hope we will figure it out.

Just to clarify, which statement is true ?
- The powbox does the pow and return the transaction back to you so you can send it to the node you want
- The powbox does the pow and send it itself to its node

Thanks

**Comment by todofixthis** [comment]
The former is correct.

When you run a full node, PyOTA prepares the transaction more-or-less offline, then sends an `attachToTangle` request to your node with the raw transaction trytes.  The node then does the PoW and sends back the resulting trytes.  PyOTA then makes some additional requests to the node to broadcast the transaction to the Tangle.

When you use the powbox node, the process is basically the same; there's just a few differences in the way PyOTA makes the `attachToTangle` request.

**Comment by lapwat** [comment]
Thanks for the clarification.
Then when using an adapter, you should be able to choose the node on which you want to perform the pow, and the node by which you want to attach to the tangle. Since they do not have to be the same, it would be nice if we can tune this parameter.

**Comment by todofixthis** [comment]
You sure can 😺  Have a look at https://pyota.readthedocs.io/en/latest/adapters.html#routingwrapper

Routers and adapters can be nested, so you could use a `RoutingWrapper` to send all non-PoW requests to a light wallet node, and send all PoW request to the powbox, via a `SandboxAdapter`.

**Comment by lapwat** [comment]
Nice! I have found nodes that are doing the PoW for you : https://nodes.iota.fm:443 and https://field.carriota.com:443. There is no need to use the PoWbox anymore :)
