### ISSUE TITLE
UTF8 decode of Trytes gives error

### ISSUE THREAD

**Issue by markschwed** [iotaledger/iota.lib.py#188]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 7: invalid start byte

from 

```
RBPC9D9DCDEABCIIGHTCFDFA999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
```

using

```python
print(str(transaction.signature_message_fragment.decode()))
```

Can anyone help me how to decode this message using Pyota?

Thanks!

also as suggested by Charlie, I tried

```python
trytes=iota.TryteString(transaction.signature_message_fragment)
print(str(iota.TryteString.from_trytes(trytes)))
```

which gives

```
Traceback (most recent call last):
  File "D:\Dropbox\GitHub\IOTA\echoiota\daemon.py", line 49, in <module>
    print(str(iota.TryteString.from_trytes(trytes)))
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\iota\types.py", line 157, in from_trytes
    chars.append(AsciiTrytesCodec.alphabet[converted])
```

https://iota.stackexchange.com/questions/1934/decode-signature-message-fragment-with-utf-8

**Comment by markschwed** [comment]
Using Trinity "Hallo Süßer!" gives:
RBPC9D9DCDEABCIIGHTCFDFA

Using s = iota.TryteString.from_unicode('Hallo Süßer!') gives:
RBPC9D9DCDEABCFGZFFGXETCFDFA

**Comment by todofixthis** [comment]
Hey @markschwed thanks for reporting this issue!  I've pinged the IOTA Foundation developers to determine whether this is an issue with Trinity or PyOTA.  Will follow up once I learn more.

**Comment by markschwed** [comment]
thanks @todofixthis, please keep me up2date!

**Comment by todofixthis** [comment]
I have confirmed that this is actually an issue with the JS library.  See https://github.com/iotaledger/iota.lib.js/issues/243 for more info.
