### ISSUE TITLE
Pyinstaller Distribution not found error

### ISSUE THREAD

**Issue by Zenkazio** [iotaledger/iota.lib.py#193]
Hey can someone help fixing this it always appears when i import iota

```
Traceback (most recent call last):
  File "pyintest.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\iota\__init__.py", line 39, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\iota\api.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\iota\commands\__init__.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\filters\__init__.py", line 13, in <module>
  File "site-packages\pkg_resources\__init__.py", line 888, in require
  File "site-packages\pkg_resources\__init__.py", line 774, in resolve
pkg_resources.DistributionNotFound: The 'filters' distribution was not found and is required by the application
```

why it has problems with filters since it installed as usual with pycharm
i m unable to find the `--paths` or `hiddenimport` to fix this

**Comment by todofixthis** [comment]
Hey @Zenkazio that's a strange one.

`filters` is declared as part of PyOTA's requirements in `setup.py`, so PyCharm should have installed it.

This may be a bug in PyCharm.  Try removing and rebuilding the virtualenv.  If it still doesn't install the filters distro, please report it on the [PyCharm issue tracker](https://youtrack.jetbrains.com/issues/PY).  The PyCharm development team are very responsive, and you'll be helping out your fellow developers 😺

As a workaround, you can install the filters distro manually.

Let me know if you are able to resolve the issue.

**Comment by Zenkazio** [comment]
Hey, thanks for answering but you got me wrong, in PyCharm the programs work like a ...Charm but the problem is building a standalone using Pyinstaller thats were this error apears if i start the .exe file

**Comment by todofixthis** [comment]
Ah... 🐍 🏅 😹 

Hm.  I'm not that familar with PyInstaller.  I had a quick look through the docs, and it recommended [a few workarounds for missing dependencies](https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html#helping-pyinstaller-find-modules), but all of them seem to be related to modules imported in a sneaky way, which PyOTA doesn't do.

Can you confirm what distros PyInstaller does install?  Is it just `filters` that is missing, or are there others?  Maybe there's a configuration issue that is preventing PyInstaller from finding any dependencies.

**Comment by Zenkazio** [comment]
i tried a few workarounds already but i will search further was just hoping that someone already build a standalone and has this issues fixed....

**Comment by todofixthis** [comment]
Sounds good!  Also, try asking in the `#python` channel on the [IOTA Discord server](https://discord.gg/7Gu2mG5).  There might be some other developers there who have run into this issue before.

**Comment by rafalf** [comment]
@Zenkazio Did you figure this out?
If so, could you post a solution

**Comment by todofixthis** [comment]
Some additional info and links to possible solutions in #341; locking this as a duplicate.

EDIT:  Solution in the thread for #341
