### ISSUE TITLE
ModuleNotFoundError when importing iota in Python 3.6/3.7

### ISSUE THREAD

**Issue by yillkid** [iotaledger/iota.lib.py#203]
## Reproduction

Code (test.py) :
`# coding=utf-8
from iota import Iota`

Output:
`$ python2.7 test.py`
`$ python3.5 test.py`
`$ python3.6 test.py`
```Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from iota import Iota
ModuleNotFoundError: No module named 'iota'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from iota import Iota
ModuleNotFoundError: No module named 'iota'

**Comment by yillkid** [comment]
The same output on Python3.7.

**Comment by todofixthis** [comment]
Hey @yillkid that's a curious error.

Colud you double-check that the pyota library is installed, and that the virtualenv is active (if applicable)?

What command are you using to install pyota?

**Comment by 01R** [comment]
Experienced this issue for 3.7, 3.6 is working tho.

**Comment by yillkid** [comment]
Reproduction
### Environment
* Ubuntu 16.04 LTS (Xenial Xerus) 

### Install Pyota
```shell
# pip install pyota
Collecting pyota
  Downloading https://files.pythonhosted.org/packages/83/8c/1269aa131b16bc031ddea470c13af0994f64c9ed0b29a7ef9703a49f93d5/PyOTA-2.0.6-py2.py3-none-any.whl (106kB)
    100% |████████████████████████████████| 112kB 1.2MB/s 
Requirement already satisfied: requests[security]>=2.4.1 in /usr/local/lib/python2.7/dist-packages (from pyota) (2.18.4)
Requirement already satisfied: typing; python_version < "3.0" in /usr/local/lib/python2.7/dist-packages (from pyota) (3.6.4)
Requirement already satisfied: filters in /usr/local/lib/python2.7/dist-packages (from pyota) (1.3.2)
Requirement already satisfied: six in ./.local/lib/python2.7/site-packages (from pyota) (1.11.0)
Requirement already satisfied: pysha3 in /usr/local/lib/python2.7/dist-packages (from pyota) (1.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests[security]>=2.4.1->pyota) (2018.4.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests[security]>=2.4.1->pyota) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests[security]>=2.4.1->pyota) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests[security]>=2.4.1->pyota) (1.22)
Requirement already satisfied: cryptography>=1.3.4; extra == "security" in /usr/local/lib/python2.7/dist-packages (from requests[security]>=2.4.1->pyota) (2.2.2)
Requirement already satisfied: pyOpenSSL>=0.14; extra == "security" in /usr/local/lib/python2.7/dist-packages (from requests[security]>=2.4.1->pyota) (18.0.0)
Requirement already satisfied: py2casefold; python_version < "3.0" in /usr/local/lib/python2.7/dist-packages (from filters->pyota) (1.0.1)
Requirement already satisfied: regex in /usr/local/lib/python2.7/dist-packages (from filters->pyota) (2018.2.21)
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from filters->pyota) (2018.4)
Requirement already satisfied: python-dateutil in /usr/local/lib/python2.7/dist-packages (from filters->pyota) (2.7.3)
Requirement already satisfied: class-registry in /usr/local/lib/python2.7/dist-packages (from filters->pyota) (2.1.2)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4; extra == "security"->requests[security]>=2.4.1->pyota) (0.24.0)
Requirement already satisfied: cffi>=1.7 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4; extra == "security"->requests[security]>=2.4.1->pyota) (1.11.5)
Requirement already satisfied: enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4; extra == "security"->requests[security]>=2.4.1->pyota) (1.1.6)
Requirement already satisfied: ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3.4; extra == "security"->requests[security]>=2.4.1->pyota) (1.0.22)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7->cryptography>=1.3.4; extra == "security"->requests[security]>=2.4.1->pyota) (2.18)
Installing collected packages: pyota
Successfully installed pyota-2.0.6
```
### Python 2.7
```shell
$ virtualenv iota-2.7 -p /usr/bin/python2.7
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/ubuntu/iota-2.7/bin/python2.7
Also creating executable in /home/ubuntu/iota-2.7/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
$ cd iota-2.7/
ubuntu@node3-puyuma:~/iota-2.7$ source bin/activate
(iota-2.7) ubuntu@node3-puyuma:~/iota-2.7$ python -V
Python 2.7.12
(iota-2.7) ubuntu@node3-puyuma:~/iota-2.7$ python 
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import iota
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named iota
>>> 
```
### Python 3.6
```
virtualenv iota-3.6 -p /usr/bin/python3.6
Running virtualenv with interpreter /usr/bin/python3.6
Using base prefix '/usr'
New python executable in /home/yillkid/iota-3.6/bin/python3.6
Also creating executable in /home/yillkid/iota-3.6/bin/python
Installing setuptools, pip, wheel...done.
$ cd iota-3.6/
yillkid@Orz:~/iota-3.6$ source bin/activate
(iota-3.6) yillkid@Orz:~/iota-3.6$ python
Python 3.6 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import iota
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'iota'
>>> 
```

**Comment by oopsmonk** [comment]
if you wanna access to the global site-packages, you should use `--system-site-packages`
It is no problem on my Ubuntu 18.04
```
$ virtualenv iota-2.7 -p /usr/bin/python2.7 --system-site-packages
$ cd iota-2.7
$ source bin/activate
$ python -c "import iota"
```
or you should install pyota in the new virtual environment.
for python3, you can install pyota via `pip3 install pyota`
