### ISSUE TITLE
Iota does not support '__isabstractmethod__' command.

### ISSUE THREAD

**Issue by timohe** [iotaledger/iota.lib.py#206]
I have code like this:

```
class IotaAdapter(Adapter):
    client = Iota('https://nodes.devnet.iota.org:443', testnet=True)
```
Where Adapter is an abstract class. (class Adapter(ABC): [...])
I am getting the error:

> iota.api.InvalidCommand: Iota does not support '__isabstractmethod__' command.

It works without a problem if I don't inherit from Adapter.
Anyone knows how I can fix this?

**Comment by todofixthis** [comment]
Hi @timohe thanks for raising this issue!

Could you confirm which version of Python you are using?

**Comment by timohe** [comment]
I am using python 3.6.6.
This is the whole thing:

```
Traceback (most recent call last):
  File "/Users/timo/Documents/repos/bc-interop/venv/lib/python3.6/site-packages/iota/api.py", line 106, in __getattr__
    command_class = self.commands[command]
KeyError: '__isabstractmethod__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/timo/Documents/repos/bc-interop/adapters/iota_adapter.py", line 10, in <module>
    class IotaAdapter(Adapter):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/abc.py", line 136, in __new__
    for name, value in namespace.items()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/abc.py", line 137, in <setcomp>
    if getattr(value, "__isabstractmethod__", False)}
  File "/Users/timo/Documents/repos/bc-interop/venv/lib/python3.6/site-packages/iota/api.py", line 111, in __getattr__
    command = command,
iota.api.InvalidCommand: Iota does not support '__isabstractmethod__' command.
```

**Comment by todofixthis** [comment]
Scheduled for release: v2.0.7
