### ISSUE TITLE
Not compatible with Python 3.7?

### ISSUE THREAD

**Issue by Nitrooo** [iotaledger/iota.lib.py#226]
Linux, `CPython 3.7.3`.
By just importing `from iota import Iota` I get:

```
Traceback (most recent call last):
  File "/home/path/main.py", line 1, in <module>
    from iota import Iota
  File "/home/path/venv/lib/python3.7/site-packages/iota/__init__.py", line 38, in <module>
    from .api import *
  File "/home/path/venv/lib/python3.7/site-packages/iota/api.py", line 12, in <module>
    from iota.commands import BaseCommand, CustomCommand, core, \
  File "/home/path/venv/lib/python3.7/site-packages/iota/commands/__init__.py", line 13, in <module>
    import filters as f
  File "/home/path/venv/lib/python3.7/site-packages/filters/__init__.py", line 27, in <module>
    from filters.extensions import FilterExtensionRegistry
  File "/home/path/venv/lib/python3.7/site-packages/filters/extensions.py", line 11, in <module>
    from class_registry import EntryPointClassRegistry
  File "/home/path/venv/lib/python3.7/site-packages/class_registry/__init__.py", line 5, in <module>
    from .registry import *
  File "/home/path/venv/lib/python3.7/site-packages/class_registry/registry.py", line 33, in <module>
    class BaseRegistry(with_metaclass(ABCMeta, Mapping)):
  File "/home/path/venv/lib/python3.7/site-packages/six.py", line 827, in __new__
    return meta(name, bases, d)
  File "/usr/lib/python3.7/abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: type() doesn't support MRO entry resolution; use types.new_class()

Process finished with exit code 1
```

**Comment by todofixthis** [comment]
Hi @Nitrooo thanks for reporting this!  Aye, the library needs a few tweaks for compatibility with Python 3.7.

Marking this issue as `help wanted`; the fix should be fairly simple; very similar to [this one](https://github.com/todofixthis/class-registry/commit/82bf9cc7a8c5a22207305af7f9d1752ed3325baa#diff-e1ca21389b7b902d0e440a278324f060R35).

**Comment by Youssefraqui** [comment]
HI, 
I do have the same issue in my side, import iota not working in my side due to :
TypeError: type() doesn't support MRO entry resolution; use types.new_class()
Will this issue be fixed soon, and when will it be published on Pypi? Otherwise, how can i resolve the issue within iota lib?
Thanks a lof in advance

**Comment by quicksell-louis** [comment]
Curious if any progress has been made on this?  I'm hoping to use pyota with Python 3.7.  Is it still not compatible?

**Comment by hukkinj1** [comment]
The `develop` branch now supports Python 3.7.  @todofixthis would it be possible to release that so we can close this issue?
